FROM scratch
MAINTAINER Jonathan Dowland <jmtd@debian.org>
ADD root.tar /
RUN echo "deb http://security.debian.org jessie/updates main contrib non-free" >> /etc/apt/sources.list
RUN apt-get update \
	&& apt-get -y upgrade \
	&& apt-get -y autoremove \
	&& apt-get clean \
	&& find /var/lib/apt/lists -type f -delete
LABEL org.redmars.docker.VcsType git
LABEL org.redmars.docker.VcsUrl  http://github.com/jmtd/debian-docker
LABEL org.redmars.docker.VcsRef  SUBSTITUTION_FAILED
CMD ["/bin/bash"]
